#ifndef __VARIABLES_H__
#define __VARIABLES_H__

#include <stdint.h>
#include <stddef.h>

extern uint32_t memory_size;
extern uint32_t kernel_size;
extern uint32_t available_page;

#define FLAGS_REGS_COUNT 191

static char *flagsNregs[FLAGS_REGS_COUNT] = {

    "rax",     "eax",     "ax",      "al",      "ah",
    "rbx",     "ebx",     "bx",      "bl",      "bh",
    "rcx",     "ecx",     "cx",      "cl",      "ch",
    "rdx",     "edx",     "dx",      "dl",      "dh",
    "rsi",     "esi",     "si",      "sil",
    "rdi",     "edi",     "di",      "dil",
    "rsp",     "esp",     "sp",      "spl",
    "rbp",     "ebp",     "bp",      "bpl",
    "rip",     "eip",     "ip",
    "st(0)",   "mm0",
    "st(1)",   "mm1",
    "st(2)",   "mm2",
    "st(3)",   "mm3",
    "st(4)",   "mm4",
    "st(5)",   "mm5",
    "st(6)",   "mm6",
    "st(7)",   "mm7",
    "zmm0",    "ymm0",    "xmm0",
    "zmm1",    "ymm1",    "xmm1",
    "zmm2",    "ymm2",    "xmm2",
    "zmm3",    "ymm3",    "xmm3",
    "zmm4",    "ymm4",    "xmm4",
    "zmm5",    "ymm5",    "xmm5",
    "zmm6",    "ymm6",    "xmm6",
    "zmm7",    "ymm7",    "xmm7",
    "zmm8",    "ymm8",    "xmm8",
    "zmm9",    "ymm9",    "xmm9",
    "zmm10",   "ymm10",   "xmm10",
    "zmm11",   "ymm11",   "xmm11",
    "zmm12",   "ymm12",   "xmm12",
    "zmm13",   "ymm13",   "xmm13",
    "zmm14",   "ymm14",   "xmm14",
    "zmm15",   "ymm15",   "xmm15",
    "zmm16",
    "zmm17",
    "zmm18",
    "zmm19",
    "zmm20",
    "zmm21",
    "zmm22",
    "zmm23",
    "zmm24",
    "zmm25",
    "zmm26",
    "zmm27",
    "zmm28",
    "zmm29",
    "zmm30",
    "zmm31",
    "cr0",     "cr1",     "cr2",     "cr3",
    "cr4",     "cr5",     "cr6",     "cr7",
    "cr8",     "cr9",     "cr10",    "cr11",
    "cr12",    "cr13",    "cr14",    "cr15",
    "dr0",     "dr1",     "dr2",     "dr3",
    "dr4",     "dr5",     "dr6",     "dr7",
    "dr8",     "dr9",     "dr10",    "dr11",
    "dr12",    "dr13",    "dr14",    "dr15",
    "cw",
    "sw",
    "tw",
    "fp_ip",
    "fp_dp",
    "fp_cs",
    "fp_ds",
    "fp_opc",
    "msw",
    "mxcsr",
    "cs",
    "ds",
    "fs",
    "gs",
    "ss",
    "es",
    "gdtr",
    "ldtr",
    "idtr",
    "tr",
    "rflags",  "eflags",  "flags",
    "cf",      "pf",      "af",      "zf",      "sf",
    "tf",      "if",      "df",      "of",      "iopl", 
    "nt",      "rf",      "vm",      "ac",      "vif", 
    "vip",     "id"

};

#endif
